services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastlibrary
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/fastlibrary
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME:-test_username}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-test_password}
      MAIL_SERVER: ${MAIL_SERVER:-smtp.example.com}
      MAIL_FROM: ${MAIL_FROM:-test@example.com}
    ports:
      - "8000:8000"
    mem_limit: 2048m
    mem_reservation: 1024m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:3000"
