name: "🎨 Styling"
description: "Visual or styling-related changes"
title: "[styling] "
labels: ["styling"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to Sonic Library! Please fill out the following details.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What visual aspect needs adjustment?
      placeholder: e.g. Add loading skeleton to book cards
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Visual Details
      description: Describe the styling or animation improvement.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Visual Completion Criteria
      placeholder: e.g. Card hover animation added
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["🟢 Low", "🟡 Medium", "🔴 High"]