"""increase size book description

Revision ID: 1c081e85c8fa
Revises: 562ab1afb223
Create Date: 2025-05-21 19:51:52.972001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c081e85c8fa'
down_revision: Union[str, None] = '562ab1afb223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'description',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
