"""improve book model

Revision ID: 854ae34e7974
Revises: 5557bd96c90e
Create Date: 2025-05-04 19:39:30.407720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854ae34e7974'
down_revision: Union[str, None] = '5557bd96c90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('books', sa.Column('publisher', sa.String(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True, max_length=13))
    op.add_column('books', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('books', sa.Column('language', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'books', ['isbn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'language')
    op.drop_column('books', 'image_url')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'publisher')
    op.drop_column('books', 'published_date')
    op.drop_column('books', 'page_count')
    # ### end Alembic commands ###
