

export const BOOK_GENRES = [
  { value: "", label: "All Genres" },
  { value: "FANTASY", label: "Fantasy" },
  { value: "SCIENCE_FICTION", label: "Science Fiction" },
  { value: "MYSTERY", label: "Mystery" },
  { value: "THRILLER", label: "Thriller" },
  { value: "ROMANCE", label: "Romance" },
  { value: "WESTERN", label: "Western" },
  { value: "DYSTOPIAN", label: "Dystopian" },
  { value: "CONTEMPORARY", label: "Contemporary" },
  { value: "HISTORICAL", label: "Historical" },
  { value: "HORROR", label: "Horror" },
  { value: "BIOGRAPHY", label: "Biography" },
  { value: "AUTOBIOGRAPHY", label: "Autobiography" },
  { value: "MEMOIR", label: "Memoir" },
  { value: "SELF_HELP", label: "Self Help" },
  { value: "HEALTH", label: "Health" },
  { value: "TRAVEL", label: "Travel" },
  { value: "GUIDE", label: "Guide" },
  { value: "RELIGION", label: "Religion" },
  { value: "SCIENCE", label: "Science" },
  { value: "HISTORY", label: "History" },
  { value: "MATH", label: "Math" },
  { value: "POETRY", label: "Poetry" },
  { value: "ART", label: "Art" },
  { value: "COOKING", label: "Cooking" },
  { value: "JOURNAL", label: "Journal" },
  { value: "DIARY", label: "Diary" },
  { value: "COMICS", label: "Comics" },
  { value: "GRAPHIC_NOVEL", label: "Graphic Novel" },
  { value: "CHILDRENS", label: "Children's" },
  { value: "YOUNG_ADULT", label: "Young Adult" }
];